import { AcEnumFileExtension } from "../enums/ac-enum-file-extension.enum";

export class AcFileUtils {
  private static readonly _mimeTypes: Record<string, string> = {
    "323": "text/h323",
    "3g2": "video/3gpp2",
    "3gp2": "video/3gpp2",
    "3gp": "video/3gpp",
    "3gpp": "video/3gpp",
    "aaf": "application/octet-stream",
    "aac": "audio/aac",
    "aca": "application/octet-stream",
    "accdb": "application/msaccess",
    "accde": "application/msaccess",
    "accdt": "application/msaccess",
    "acx": "application/internet-property-stream",
    "adt": "audio/vnd.dlna.adts",
    "adts": "audio/vnd.dlna.adts",
    "afm": "application/octet-stream",
    "ai": "application/postscript",
    "aif": "audio/x-aiff",
    "aifc": "audio/aiff",
    "aiff": "audio/aiff",
    "application": "application/x-ms-application",
    "art": "image/x-jg",
    "asd": "application/octet-stream",
    "asf": "video/x-ms-asf",
    "asi": "application/octet-stream",
    "asm": "text/plain",
    "asr": "video/x-ms-asf",
    "asx": "video/x-ms-asf",
    "atom": "application/atom+xml",
    "au": "audio/basic",
    "avi": "video/avi",
    "axs": "application/olescript",
    "bas": "text/plain",
    "bcpio": "application/x-bcpio",
    "bin": "application/octet-stream",
    "bmp": "image/bmp",
    "c": "text/plain",
    "cab": "application/vnd.ms-cab-compressed",
    "calx": "application/vnd.ms-office.calx",
    "cat": "application/vnd.ms-pki.seccat",
    "cdf": "application/x-cdf",
    "chm": "application/octet-stream",
    "class": "application/x-java-applet",
    "clp": "application/x-msclip",
    "cmx": "image/x-cmx",
    "cnf": "text/plain",
    "cod": "image/cis-cod",
    "cpio": "application/x-cpio",
    "cpp": "text/plain",
    "crd": "application/x-mscardfile",
    "crl": "application/pkix-crl",
    "crt": "application/x-x509-ca-cert",
    "csh": "application/x-csh",
    "css": "text/css",
    "csv": "application/octet-stream",
    "cur": "application/octet-stream",
    "dcr": "application/x-director",
    "deploy": "application/octet-stream",
    "der": "application/x-x509-ca-cert",
    "dib": "image/bmp",
    "dir": "application/x-director",
    "disco": "text/xml",
    "dll": "application/x-msdownload",
    "dllconfig": "text/xml",
    "dlm": "text/dlm",
    "doc": "application/msword",
    "docm": "application/vnd.ms-word.document.macroEnabled.12",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "dot": "application/msword",
    "dotm": "application/vnd.ms-word.template.macroEnabled.12",
    "dotx": "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    "dsp": "application/octet-stream",
    "dtd": "text/xml",
    "dvi": "application/x-dvi",
    "dvr_ms": "video/x-ms-dvr",
    "dwf": "drawing/x-dwf",
    "dwp": "application/octet-stream",
    "dxr": "application/x-director",
    "eml": "message/rfc822",
    "emz": "application/octet-stream",
    "eot": "application/vnd.ms-fontobject",
    "eps": "application/postscript",
    "etx": "text/x-setext",
    "evy": "application/envoy",
    "exe": "application/octet-stream",
    "execonfig": "text/xml",
    "fdf": "application/vnd.fdf",
    "fif": "application/fractals",
    "fla": "application/octet-stream",
    "flr": "x-world/x-vrml",
    "flv": "video/x-flv",
    "gif": "image/gif",
    "gtar": "application/x-gtar",
    "gz": "application/x-gzip",
    "h": "text/plain",
    "hdf": "application/x-hdf",
    "hdml": "text/x-hdml",
    "hhc": "application/x-oleobject",
    "hhk": "application/octet-stream",
    "hhp": "application/octet-stream",
    "hlp": "application/winhlp",
    "hqx": "application/mac-binhex40",
    "hta": "application/hta",
    "htc": "text/x-component",
    "htm": "text/html",
    "html": "text/html",
    "htt": "text/webviewhtml",
    "hxt": "text/html",
    "ico": "image/x-icon",
    "ics": "text/calendar",
    "ief": "image/ief",
    "iii": "application/x-iphone",
    "inf": "application/octet-stream",
    "ins": "application/x-internet-signup",
    "isp": "application/x-internet-signup",
    "ivf": "video/x-ivf",
    "jar": "application/java-archive",
    "java": "application/octet-stream",
    "jck": "application/liquidmotion",
    "jcz": "application/liquidmotion",
    "jfif": "image/pjpeg",
    "jpb": "application/octet-stream",
    "jpe": "image/jpeg",
    "jpeg": "image/jpeg",
    "jpg": "image/jpeg",
    "js": "application/javascript",
    "jsx": "text/jscript",
    "latex": "application/x-latex",
    "lit": "application/x-ms-reader",
    "lpk": "application/octet-stream",
    "lsf": "video/x-la-asf",
    "lsx": "video/x-la-asf",
    "lzh": "application/octet-stream",
    "m13": "application/x-msmediaview",
    "m14": "application/x-msmediaview",
    "m1v": "video/mpeg",
    "m2ts": "video/vnd.dlna.mpeg-tts",
    "m3u": "audio/x-mpegurl",
    "m4a": "audio/mp4",
    "m4v": "video/mp4",
    "man": "application/x-troff-man",
    "manifest": "application/x-ms-manifest",
    "map": "text/plain",
    "mdb": "application/x-msaccess",
    "mdp": "application/octet-stream",
    "me": "application/x-troff-me",
    "mht": "message/rfc822",
    "mhtml": "message/rfc822",
    "mid": "audio/mid",
    "midi": "audio/mid",
    "mix": "application/octet-stream",
    "mmf": "application/x-smaf",
    "mno": "text/xml",
    "mny": "application/x-msmoney",
    "mov": "video/quicktime",
    "movie": "video/x-sgi-movie",
    "mp2": "video/mpeg",
    "mp3": "audio/mpeg",
    "mp4": "video/mp4",
    "mp4v": "video/mp4",
    "mpa": "video/mpeg",
    "mpe": "video/mpeg",
    "mpeg": "video/mpeg",
    "mpg": "video/mpeg",
    "mpp": "application/vnd.ms-project",
    "mpv2": "video/mpeg",
    "ms": "application/x-troff-ms",
    "msi": "application/octet-stream",
    "mso": "application/octet-stream",
    "mvb": "application/x-msmediaview",
    "mvc": "application/x-miva-compiled",
    "nc": "application/x-netcdf",
    "nsc": "video/x-ms-asf",
    "nws": "message/rfc822",
    "ocx": "application/octet-stream",
    "oda": "application/oda",
    "odc": "text/x-ms-odc",
    "ods": "application/oleobject",
    "oga": "audio/ogg",
    "ogg": "video/ogg",
    "ogv": "video/ogg",
    "one": "application/onenote",
    "onea": "application/onenote",
    "onetoc": "application/onenote",
    "onetoc2": "application/onenote",
    "onetmp": "application/onenote",
    "onepkg": "application/onenote",
    "osdx": "application/opensearchdescription+xml",
    "otf": "font/otf",
    "p10": "application/pkcs10",
    "p12": "application/x-pkcs12",
    "p7b": "application/x-pkcs7-certificates",
    "p7c": "application/pkcs7-mime",
    "p7m": "application/pkcs7-mime",
    "p7r": "application/x-pkcs7-certreqresp",
    "p7s": "application/pkcs7-signature",
    "pbm": "image/x-portable-bitmap",
    "pcx": "application/octet-stream",
    "pcz": "application/octet-stream",
    "pdf": "application/pdf",
    "pfb": "application/octet-stream",
    "pfm": "application/octet-stream",
    "pfx": "application/x-pkcs12",
    "pgm": "image/x-portable-graymap",
    "pko": "application/vnd.ms-pki.pko",
    "pma": "application/x-perfmon",
    "pmc": "application/x-perfmon",
    "pml": "application/x-perfmon",
    "pmr": "application/x-perfmon",
    "pmw": "application/x-perfmon",
    "png": "image/png",
    "pnm": "image/x-portable-anymap",
    "pnz": "image/png",
    "pot": "application/vnd.ms-powerpoint",
    "potm": "application/vnd.ms-powerpoint.template.macroEnabled.12",
    "potx": "application/vnd.openxmlformats-officedocument.presentationml.template",
    "ppam": "application/vnd.ms-powerpoint.addin.macroEnabled.12",
    "ppm": "image/x-portable-pixmap",
    "pps": "application/vnd.ms-powerpoint",
    "ppsm": "application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
    "ppsx": "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    "ppt": "application/vnd.ms-powerpoint",
    "pptm": "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "prf": "application/pics-rules",
    "prm": "application/octet-stream",
    "prx": "application/octet-stream",
    "ps": "application/postscript",
    "psd": "application/octet-stream",
    "psm": "application/octet-stream",
    "psp": "application/octet-stream",
    "pub": "application/x-mspublisher",
    "qt": "video/quicktime",
    "qtl": "application/x-quicktimeplayer",
    "qxd": "application/octet-stream",
    "ra": "audio/x-pn-realaudio",
    "ram": "audio/x-pn-realaudio",
    "rar": "application/octet-stream",
    "ras": "image/x-cmu-raster",
    "rf": "image/vnd.rn-realflash",
    "rgb": "image/x-rgb",
    "rm": "application/vnd.rn-realmedia",
    "rmi": "audio/mid",
    "roff": "application/x-troff",
    "rpm": "audio/x-pn-realaudio-plugin",
    "rtf": "application/rtf",
    "rtx": "text/richtext",
    "scd": "application/x-msschedule",
    "sct": "text/scriptlet",
    "sea": "application/octet-stream",
    "setpay": "application/set-payment-initiation",
    "setreg": "application/set-registration-initiation",
    "sgml": "text/sgml",
    "sh": "application/x-sh",
    "shar": "application/x-shar",
    "sit": "application/x-stuffit",
    "sldm": "application/vnd.ms-powerpoint.slide.macroEnabled.12",
    "sldx": "application/vnd.openxmlformats-officedocument.presentationml.slide",
    "smd": "audio/x-smd",
    "smi": "application/octet-stream",
    "smx": "audio/x-smd",
    "smz": "audio/x-smd",
    "snd": "audio/basic",
    "snp": "application/octet-stream",
    "spc": "application/x-pkcs7-certificates",
    "spl": "application/futuresplash",
    "spx": "audio/ogg",
    "src": "application/x-wais-source",
    "ssm": "application/streamingmedia",
    "sst": "application/vnd.ms-pki.certstore",
    "stl": "application/vnd.ms-pki.stl",
    "sv4cpio": "application/x-sv4cpio",
    "sv4crc": "application/x-sv4crc",
    "svg": "image/svg+xml",
    "svgz": "image/svg+xml",
    "swf": "application/x-shockwave-flash",
    "t": "application/x-troff",
    "tar": "application/x-tar",
    "tcl": "application/x-tcl",
    "tex": "application/x-tex",
    "texi": "application/x-texinfo",
    "texinfo": "application/x-texinfo",
    "tgz": "application/x-compressed",
    "thmx": "application/vnd.ms-officetheme",
    "thn": "application/octet-stream",
    "tif": "image/tiff",
    "tiff": "image/tiff",
    "toc": "application/octet-stream",
    "tr": "application/x-troff",
    "trm": "application/x-msterminal",
    "ts": "video/vnd.dlna.mpeg-tts",
    "tsv": "text/tab-separated-values",
    "ttf": "application/octet-stream",
    "tts": "video/vnd.dlna.mpeg-tts",
    "txt": "text/plain",
    "u32": "application/octet-stream",
    "uls": "text/iuls",
    "ustar": "application/x-ustar",
    "vbs": "text/vbscript",
    "vcf": "text/x-vcard",
    "vcs": "text/plain",
    "vdx": "application/vnd.ms-visio.viewer",
    "vml": "text/xml",
    "vsd": "application/vnd.visio",
    "vss": "application/vnd.visio",
    "vst": "application/vnd.visio",
    "vsto": "application/x-ms-vsto",
    "vsw": "application/vnd.visio",
    "vsx": "application/vnd.visio",
    "vtx": "application/vnd.visio",
    "wav": "audio/wav",
    "wax": "audio/x-ms-wax",
    "wbmp": "image/vnd.wap.wbmp",
    "wcm": "application/vnd.ms-works",
    "wdb": "application/vnd.ms-works",
    "webm": "video/webm",
    "wks": "application/vnd.ms-works",
    "wm": "video/x-ms-wm",
    "wma": "audio/x-ms-wma",
    "wmd": "application/x-ms-wmd",
    "wmf": "application/x-msmetafile",
    "wml": "text/vnd.wap.wml",
    "wmlc": "application/vnd.wap.wmlc",
    "wmls": "text/vnd.wap.wmlscript",
    "wmlsc": "application/vnd.wap.wmlscriptc",
    "wmp": "video/x-ms-wmp",
    "wmv": "video/x-ms-wmv",
    "wmx": "video/x-ms-wmx",
    "wmz": "application/x-ms-wmz",
    "woff": "font/x-woff",
    "wps": "application/vnd.ms-works",
    "wri": "application/x-mswrite",
    "wrl": "x-world/x-vrml",
    "wrz": "x-world/x-vrml",
    "wsdl": "text/xml",
    "wtv": "video/x-ms-wtv",
    "wvx": "video/x-ms-wvx",
    "x": "application/directx",
    "xaf": "x-world/x-vrml",
    "xaml": "application/xaml+xml",
    "xap": "application/x-silverlight-app",
    "xbap": "application/x-ms-xbap",
    "xbm": "image/x-xbitmap",
    "xdr": "text/plain",
    "xht": "application/xhtml+xml",
    "xhtml": "application/xhtml+xml",
    "xla": "application/vnd.ms-excel",
    "xlam": "application/vnd.ms-excel.addin.macroEnabled.12",
    "xlc": "application/vnd.ms-excel",
    "xlm": "application/vnd.ms-excel",
    "xls": "application/vnd.ms-excel",
    "xlsb": "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
    "xlsm": "application/vnd.ms-excel.sheet.macroEnabled.12",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "xlt": "application/vnd.ms-excel",
    "xltm": "application/vnd.ms-excel.template.macroEnabled.12",
    "xltx": "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    "xlw": "application/vnd.ms-excel",
    "xml": "text/xml",
    "xof": "x-world/x-vrml",
    "xpm": "image/x-xpixmap",
    "xps": "application/vnd.ms-xpsdocument",
    "xsd": "text/xml",
    "xsf": "text/xml",
    "xsl": "text/xml",
    "xslt": "text/xml",
    "xsn": "application/octet-stream",
    "xtp": "application/octet-stream",
    "xwd": "image/x-xwindowdump",
    "z": "application/x-compress",
    "zip": "application/x-zip-compressed"
  };

  private static readonly _fileDetails:any = {
  [AcEnumFileExtension.Aac]: { name: 'AAC Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Aaf]: { name: 'AAF Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Aca]: { name: 'ACA File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Accdb]: { name: 'Microsoft Access Database', type: 'document', svg: "database" },
  [AcEnumFileExtension.Accde]: { name: 'Microsoft Access Executable', type: 'document', svg: "database" },
  [AcEnumFileExtension.Accdt]: { name: 'Microsoft Access Database Template', type: 'document', svg: "database" },
  [AcEnumFileExtension.Acx]: { name: 'ACX File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Adt]: { name: 'ADT File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Adts]: { name: 'ADTS Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Afm]: { name: 'AFM Font File', type: 'font', svg: "file" },
  [AcEnumFileExtension.Ai]: { name: 'Adobe Illustrator File', type: 'image', svg: "image" },
  [AcEnumFileExtension.Aif]: { name: 'AIFF Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Aifc]: { name: 'AIFF-C Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Aiff]: { name: 'AIFF Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Application]: { name: 'Application File', type: 'executable', svg: "file" },
  [AcEnumFileExtension.Art]: { name: 'Art File', type: 'image', svg: "image" },
  [AcEnumFileExtension.Asd]: { name: 'AutoSave Document', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Asf]: { name: 'Advanced Streaming Format', type: 'video', svg: "video" },
  [AcEnumFileExtension.Asi]: { name: 'ASI File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Asm]: { name: 'Assembly File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Asr]: { name: 'ASR File', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Asx]: { name: 'ASX File', type: 'video', svg: "video" },
  [AcEnumFileExtension.Atom]: { name: 'Atom Feed', type: 'data', svg: "table" },
  [AcEnumFileExtension.Au]: { name: 'AU Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Avi]: { name: 'AVI Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Axs]: { name: 'AXS File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Bas]: { name: 'BAS File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Bcpio]: { name: 'BCPIO Archive', type: 'archive', svg: "fileZipper" },
  [AcEnumFileExtension.Bin]: { name: 'Binary File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Bmp]: { name: 'Bitmap Image', type: 'image', svg: "image" },
  [AcEnumFileExtension.C]: { name: 'C Source Code', type: 'code', svg: "code" },
  [AcEnumFileExtension.Cab]: { name: 'CAB Archive', type: 'archive', svg: "fileZipper" },
  [AcEnumFileExtension.Calx]: { name: 'Microsoft Excel CALX File', type: 'document', svg: "table" },
  [AcEnumFileExtension.Cat]: { name: 'Catalog File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Cdf]: { name: 'Common Data Format', type: 'data', svg: "file" },
  [AcEnumFileExtension.Chm]: { name: 'Compiled HTML Help', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Class]: { name: 'Java Class File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Clp]: { name: 'Clipboard File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Cmx]: { name: 'Corel Metafile Exchange', type: 'image', svg: "image" },
  [AcEnumFileExtension.Cnf]: { name: 'Configuration File', type: 'system', svg: "gear" },
  [AcEnumFileExtension.Cod]: { name: 'COD File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Cpio]: { name: 'CPIO Archive', type: 'archive', svg: "fileZipper" },
  [AcEnumFileExtension.Cpp]: { name: 'C++ Source Code', type: 'code', svg: "code" },
  [AcEnumFileExtension.Crd]: { name: 'Card File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Crl]: { name: 'Certificate Revocation List', type: 'data', svg: "file" },
  [AcEnumFileExtension.Crt]: { name: 'Certificate File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Csh]: { name: 'C Shell Script', type: 'code', svg: "code" },
  [AcEnumFileExtension.Css]: { name: 'Cascading Style Sheets', type: 'code', svg: "palette" },
  [AcEnumFileExtension.Csv]: { name: 'Comma-Separated Values', type: 'document', svg: "table" },
  [AcEnumFileExtension.Cur]: { name: 'Cursor File', type: 'image', svg: "image" },
  [AcEnumFileExtension.Dcr]: { name: 'Director Resource', type: 'data', svg: "file" },
  [AcEnumFileExtension.Deploy]: { name: 'Deployment Descriptor', type: 'data', svg: "file" },
  [AcEnumFileExtension.Der]: { name: 'DER Encoded Certificate', type: 'data', svg: "file" },
  [AcEnumFileExtension.Dib]: { name: 'Device Independent Bitmap', type: 'image', svg: "image" },
  [AcEnumFileExtension.Dir]: { name: 'Directory File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Disco]: { name: 'Discovery File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Dll]: { name: 'Dynamic Link Library', type: 'executable', svg: "file" },
  [AcEnumFileExtension.Dllconfig]: { name: 'DLL Configuration File', type: 'system', svg: "gear" },
  [AcEnumFileExtension.Dlm]: { name: 'Data Log Module', type: 'data', svg: "file" },
  [AcEnumFileExtension.Doc]: { name: 'Microsoft Word Document', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Docm]: { name: 'Microsoft Word Macro-Enabled Document', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Docx]: { name: 'Microsoft Word Document (OpenXML)', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Dot]: { name: 'Microsoft Word Template', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Dotm]: { name: 'Microsoft Word Macro-Enabled Template', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Dotx]: { name: 'Microsoft Word Template (OpenXML)', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Dsp]: { name: 'DSP File', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Dtd]: { name: 'Document Type Definition', type: 'code', svg: "code" },
  [AcEnumFileExtension.Dvi]: { name: 'DeVice Independent File', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.DvrMs]: { name: 'Microsoft DVR-MS Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Dwf]: { name: 'Design Web Format', type: 'data', svg: "file" },
  [AcEnumFileExtension.Dwp]: { name: 'Dynamic Web Page', type: 'data', svg: "file" },
  [AcEnumFileExtension.Dxr]: { name: 'Director Movie File', type: 'video', svg: "video" },
  [AcEnumFileExtension.Eml]: { name: 'Email File', type: 'document', svg: "envelope" },
  [AcEnumFileExtension.Emz]: { name: 'Compressed EMF File', type: 'image', svg: "image" },
  [AcEnumFileExtension.Eot]: { name: 'Embedded OpenType Font', type: 'font', svg: "font" },
  [AcEnumFileExtension.Eps]: { name: 'Encapsulated PostScript', type: 'image', svg: "image" },
  [AcEnumFileExtension.Etx]: { name: 'EText File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Evy]: { name: 'Evy File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Exe]: { name: 'Executable File', type: 'executable', svg: "arrowPointer" },
  [AcEnumFileExtension.F90]: { name: 'Fortran 90 Source File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Fbx]: { name: 'FBX File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Fdf]: { name: 'Form Data Format', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Flf]: { name: 'Flf File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Fox]: { name: 'FoxPro Database File', type: 'document', svg: "database" },
  [AcEnumFileExtension.Fpx]: { name: 'FlashPix Image', type: 'image', svg: "image" },
  [AcEnumFileExtension.Fst]: { name: 'FST File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Ftl]: { name: 'FTL File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Ftn]: { name: 'FTN File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Gbx]: { name: 'GBX File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Gdb]: { name: 'GDB File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Gds]: { name: 'GDS File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Gitignore]: { name: 'Git Ignore File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Gpx]: { name: 'GPS Exchange File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Gsi]: { name: 'GSI File', type: 'data', svg: "file" },
  [AcEnumFileExtension.H]: { name: 'Header File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Har]: { name: 'HTTP Archive File', type: 'data', svg: "boxArchive" },
  [AcEnumFileExtension.Hbm]: { name: 'Hibernate Mapping File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Hdd]: { name: 'HDD File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Htm]: { name: 'HTML File', type: 'document', svg: "globe" },
  [AcEnumFileExtension.Html]: { name: 'HTML File', type: 'document', svg: "globe" },
  [AcEnumFileExtension.Iam]: { name: 'IAM File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Icd]: { name: 'ICD File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Ics]: { name: 'iCalendar File', type: 'data', svg: "calendar" },
  [AcEnumFileExtension.Idml]: { name: 'InDesign Markup Language', type: 'document', svg: "code" },
  [AcEnumFileExtension.Iex]: { name: 'IEX File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Ips]: { name: 'IPS File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Its]: { name: 'ITS File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Iv]: { name: 'IV File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Java]: { name: 'Java Source File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Jpeg]: { name: 'JPEG Image', type: 'image', svg: "image" },
  [AcEnumFileExtension.Jpg]: { name: 'JPEG Image', type: 'image', svg: "image" },
  [AcEnumFileExtension.Json]: { name: 'JSON File', type: 'data', svg: "code" },
  [AcEnumFileExtension.Jsonp]: { name: 'JSONP File', type: 'data', svg: "code" },
  [AcEnumFileExtension.Jsp]: { name: 'JavaServer Pages File', type: 'code', svg: "code" },
  [AcEnumFileExtension.Key]: { name: 'Keynote Presentation', type: 'document', svg: "fileLines" },
  [AcEnumFileExtension.Kml]: { name: 'KML File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Let]: { name: 'Let File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Lua]: { name: 'Lua Script', type: 'code', svg: "code" },
  [AcEnumFileExtension.Lzma]: { name: 'LZMA Compressed File', type: 'archive', svg: "fileZipper" },
  [AcEnumFileExtension.M4a]: { name: 'MPEG-4 Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.M4b]: { name: 'MPEG-4 Audio Book', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.M4v]: { name: 'MPEG-4 Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.M4p]: { name: 'MPEG-4 Protected Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Mdb]: { name: 'Microsoft Access Database', type: 'document', svg: "database" },
  [AcEnumFileExtension.Mid]: { name: 'MIDI File', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Mkv]: { name: 'Matroska Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Mobi]: { name: 'Mobipocket eBook', type: 'document', svg: "book" },
  [AcEnumFileExtension.Mov]: { name: 'QuickTime Movie', type: 'video', svg: "video" },
  [AcEnumFileExtension.Mp3]: { name: 'MP3 Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Mp4]: { name: 'MPEG-4 Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Mp4a]: { name: 'MPEG-4 Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Mp4v]: { name: 'MPEG-4 Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Mpg]: { name: 'MPEG Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Msi]: { name: 'Microsoft Installer File', type: 'executable', svg: "file" },
  [AcEnumFileExtension.Odp]: { name: 'OpenDocument Presentation', type: 'document', svg: "fileLines" },
  [AcEnumFileExtension.Ods]: { name: 'OpenDocument Spreadsheet', type: 'document', svg: "table" },
  [AcEnumFileExtension.Odt]: { name: 'OpenDocument Text', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.P7b]: { name: 'PKCS#7 Certificate', type: 'data', svg: "certificate" },
  [AcEnumFileExtension.Pem]: { name: 'Privacy Enhanced Mail', type: 'data', svg: "file" },
  [AcEnumFileExtension.Pkg]: { name: 'Package File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Pl]: { name: 'Perl Script', type: 'code', svg: "code" },
  [AcEnumFileExtension.Png]: { name: 'PNG Image', type: 'image', svg: "image" },
  [AcEnumFileExtension.Ppt]: { name: 'PowerPoint Presentation', type: 'document', svg: "fileLines" },
  [AcEnumFileExtension.Pptx]: { name: 'PowerPoint Presentation (OpenXML)', type: 'document', svg: "fileLines" },
  [AcEnumFileExtension.Psd]: { name: 'Photoshop Document', type: 'image', svg: "image" },
  [AcEnumFileExtension.Rar]: { name: 'RAR Archive', type: 'archive', svg: "fileZipper" },
  [AcEnumFileExtension.Rd]: { name: 'R Markdown File', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Rtf]: { name: 'Rich Text Format', type: 'document',svg: "fileLines" },
  [AcEnumFileExtension.Sql]: { name: 'SQL Script File', type: 'script', svg: "database" },
  [AcEnumFileExtension.Srt]: { name: 'SubRip Subtitle', type: 'subtitle', svg: "file" },
  [AcEnumFileExtension.Svg]: { name: 'Scalable Vector Graphics', type: 'image', svg: "image" },
  [AcEnumFileExtension.Tar]: { name: 'TAR Archive', type: 'archive', svg: "fileZipper" },
  [AcEnumFileExtension.Tiff]: { name: 'TIFF Image', type: 'image', svg: "image" },
  [AcEnumFileExtension.Txt]: { name: 'Text File', type: 'document', svg: "text" },
  [AcEnumFileExtension.Vcf]: { name: 'vCard File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Wa]: { name: 'WA File', type: 'data', svg: "file" },
  [AcEnumFileExtension.Wav]: { name: 'WAV Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Webm]: { name: 'WebM Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Webp]: { name: 'WebP Image', type: 'image', svg: "image" },
  [AcEnumFileExtension.Wma]: { name: 'Windows Media Audio', type: 'audio', svg: "volumeHigh" },
  [AcEnumFileExtension.Wmv]: { name: 'Windows Media Video', type: 'video', svg: "video" },
  [AcEnumFileExtension.Xml]: { name: 'XML File', type: 'data', svg: "code" },
  [AcEnumFileExtension.Xls]: { name: 'Microsoft Excel File', type: 'document', svg: "table" },
  [AcEnumFileExtension.Xlsx]: { name: 'Microsoft Excel File (OpenXML)', type: 'document', svg: "table" },
  [AcEnumFileExtension.Zip]: { name: 'ZIP Archive', type: 'archive', svg: "fileZipper" },
  };

  static detailsFromExtension({ extension }: { extension: string }): {name:string,svg:string,type:string} | undefined {
    return AcFileUtils._fileDetails[extension.toLowerCase()];
  }

  static mimeFromExtension({ extension }: { extension: string }): string | undefined {
    return AcFileUtils._mimeTypes[extension.toLowerCase()];
  }

  static mimeFromPath({ path }: { path: string }): string | undefined {
    const ext = path.split('.').pop()?.toLowerCase() ?? '';
    return AcFileUtils.mimeFromExtension({ extension: ext });
  }

  static mimeFromFileName({ filename }: { filename: string }): string | undefined {
    return AcFileUtils.mimeFromPath({ path: filename });
  }

  static mimeFromFile({ file }: { file: { path?: string, name?: string } }): string | undefined {
    const filePath = file.path || file.name || '';
    return AcFileUtils.mimeFromPath({ path: filePath });
  }

  static mimeFromPathOrDefault({ path, defaultType = 'application/octet-stream' }: {
    path: string,
    defaultType?: string
  }): string {
    return AcFileUtils.mimeFromPath({ path }) ?? defaultType;
  }
}
