export enum AcEnumConditionOperator {
  Between = "BETWEEN",
  Contains = "CONTAINS",
  EndsWith = "ENDS_WITH",
  EqualTo = "EQUAL_TO",
  GreaterThan = "GREATER_THAN",
  GreaterThanEqualTo = "GREATER_THAN_EQUAL_TO",
  In = "IN",
  IsEmpty = "IS_EMPTY",
  IsNotEmpty = "IS_NOT_EMPTY",
  IsNotNull = "IS_NOT_NULL",
  IsNull = "IS_NULL",
  LessThan = "LESS_THAN",
  LessThanEqualTo = "LESS_THAN_EQUAL_TO",
  NotContains = "NOT_CONTAINS",
  NotIn = "NOT_IN",
  NotEqualTo = "NOT_EQUAL_TO",
  StartsWith = "STARTS_WITH",
  Unknown = "UNKNOWN",
}
