export enum AcEnumProgrammingLanguage {
  TypeScript = 'TYPESCRIPT',
  JavaScript = 'JAVASCRIPT',
  Dart = 'DART',
  Php = 'PHP',
  CSharp = 'CSHARP',
  Java = 'JAVA',
  Python = 'PYTHON',
  Go = 'GO',
  Kotlin = 'KOTLIN',
  Swift = 'SWIFT',
  Ruby = 'RUBY',
  Rust = 'RUST',
  C = 'C',
  CPP = 'CPP',
  ObjectiveC = 'OBJECTIVEC',
  Scala = 'SCALA',
  Perl = 'PERL',
  Haskell = 'HASKELL',
  Sql = 'SQL',
  Shell = 'SHELL',
  Yaml = 'YAML',
  Json = 'JSON',
}
