export enum AcEnumStringCase {
  Camel = "CAMEL",
  CamelSnake = "CAMEL_SNAKE",
  Capital = "CAPITAL",
  CapitalSnake = "CAPITAL_SNAKE",
  Cobol = "COBOL",
  Dot = "DOT",
  Kebab = "KEBAB",
  Lower = "LOWER",
  Pascal = "PASCAL",
  PascalSnake = "PASCAL_SNAKE",
  ScreamingSnake = "SCREAMING_SNAKE",
  Sentence = "SENTENCE",
  Snake = "SNAKE",
  Train = "TRAIN",
  Upper = "UPPER",
}
