export enum AcEnumStringCase {
  Camel = "camel",
  CamelSnake = "camel_snake",
  Capital = "capital",
  CapitalSnake = "capital_snake",
  Cobol = "cobol",
  Dot = "dot",
  Kebab = "kebab",
  Lower = "lower",
  Pascal = "pascal",
  PascalSnake = "pascal_snake",
  ScreamingSnake = "screaming_snake",
  Sentence = "sentence",
  Snake = "snake",
  Train = "train",
  Upper = "upper",
}
