export enum AcEnumProgrammingLanguage {
  TypeScript = 'typescript',
  JavaScript = 'javascript',
  Dart = 'dart',
  Php = 'php',
  CSharp = 'csharp',
  Java = 'java',
  Python = 'python',
  Go = 'go',
  Kotlin = 'kotlin',
  Swift = 'swift',
  Ruby = 'ruby',
  Rust = 'rust',
  C = 'c',
  CPP = 'cpp',
  ObjectiveC = 'objectivec',
  Scala = 'scala',
  Perl = 'perl',
  Haskell = 'haskell',
  Sql = 'sql',
  Shell = 'shell',
  Yaml = 'yaml',
  Json = 'json',
}
