export const AC_REPORT_ATTRIBUTE = {
  dataRepeater: 'ac-data-repeater',
  dataRow: 'ac-data-row',
  page: 'ac-page',
  pageBody: 'ac-page-body',
  pageFooter: 'ac-page-footer',
  pageHeader: 'ac-page-header',
  pageOrientation: 'ac-page-orientation',
  pageSize: 'ac-page-size',
  report: 'ac-report',
  reportFooter: 'ac-report-footer',
  reportHeader: 'ac-report-header',
  templateBindAttribute : 'ac:bind',
  templateClass : 'ac:class',
  templateElse: 'ac:else',
  templateElseIf: 'ac:elseif',
  templateFor : 'ac:for',
  templateIf: 'ac:if',
  templateLet: 'ac:let',
  templateStyle : 'ac:style',
  templateSwitch : 'ac:switch',
  templateSwitchCase : 'ac:switch:case',
  templateSwitchDefault : 'ac:switch:default',
  tempId:'ac-temp-id'
}
