export enum AcEnumRemoteDaoOperation{
  CheckDatabaseExist = 'CHECK_DATABASE_EXIST',
  CheckTableExist = 'CHECK_TABLE_EXIST',
  CreateDatabase = 'CREATE_DATABASE',
  DeleteRows = 'DELETE_ROWS',
  ExecuteMultipleSqlStatements = 'EXECUTE_MULTIPLE_SQL_STATEMENTS',
  ExecuteStatement = 'EXECUTE_STATEMENT',
  FormatRow = 'FORMAT_ROW',
  GetDatabaseTables = 'GET_DATABASE_TABLES',
  GetDatabaseTriggers = 'GET_DATABASE_TRIGGERS',
  GetDatabaseViews = 'GET_DATABASE_VIEWS',
  GetRows = 'GET_ROWS',
  GetTableColumns = 'GET_TABLE_COLUMNS',
  GetViewColumns = 'GET_VIEW_COLUMNS',
  InsertRow = 'INSERT_ROW',
  InsertRows = 'INSERT_ROWS',
  UpdateRow = 'UPDATE_ROW',
  UpdateRows = 'UPDATE_ROWS'
}
