
export const AC_DATA_MANAGER_EVENT = {
  BeforeDataChange : 'beforeDataChange',
  BeforeGetOnDemandData : 'beforeGetOnDemandData',
  BeforeRowAdd:'beforeRowAdd',
  DataChange : 'dataChange',
  DataFoundForFirstTime : 'dataFoundForFirstTime',
  DataRowInstanceCreate : 'dataSourceInstanceCreate',
  DisplayedRowsChange : 'displayedRowsChange',
  GetOnDemandDataSuccessCallback : 'getOnDemandDataSuccessCallback',
  OnDemandFunctionSet : 'onDemandFunctionSet',
  RefreshRows : 'refreshRows',
  Reset : 'reset',
  RowAdd : 'rowAdd',
  RowCreate : 'rowCreate',
  RowDelete : 'rowDelete',
  RowUpdate : 'rowUpdate',
  SearchQueryChange : 'searchQueryChange',
  TotalRowsChange : 'totalRowsChange',
  Unknown : 'unknown',
}
