import { AcBuilderElementsManager } from '@autocode-ts/ac-builder';
import { AC_BUILDER_BS_ACCORDION_ELEMENT } from '../elements/ac-bs-accordion.element';
import { AC_BUILDER_BS_ALERT_ELEMENT } from '../elements/ac-bs-alert.element';
import { AC_BUILDER_BS_BADGE_ELEMENT } from '../elements/ac-bs-badge.element';
import { AC_BUILDER_BS_BREADCRUMB_ELEMENT } from '../elements/ac-bs-breadcrumb.element';
import { AC_BUILDER_BS_BUTTON_GROUP_ELEMENT } from '../elements/ac-bs-button-group.element';
import { AC_BUILDER_BS_BUTTON_ELEMENT } from '../elements/ac-bs-button.element';
import { AC_BUILDER_BS_CARD_ELEMENT } from '../elements/ac-bs-card.element';
import { AC_BUILDER_BS_CAROUSEL_ELEMENT } from '../elements/ac-bs-carousel.element';
import { AC_BUILDER_BS_CHECKBOX_ELEMENT } from '../elements/ac-bs-checkbox.element';
import { AC_BUILDER_BS_COLLAPSE_ELEMENT } from '../elements/ac-bs-collapse.element';
import { AC_BUILDER_BS_COL_ELEMENT } from '../elements/ac-bs-col.element';
import { AC_BUILDER_BS_CONTAINER_ELEMENT } from '../elements/ac-bs-container.element';
import { AC_BUILDER_BS_DROPDOWN_ELEMENT } from '../elements/ac-bs-dropdown.element';
import { AC_BUILDER_BS_FIGURE_ELEMENT } from '../elements/ac-bs-figure.element';
import { AC_BUILDER_BS_FLOATING_LABEL_ELEMENT } from '../elements/ac-bs-floating-label.element';
import { AC_BUILDER_BS_FORM_ELEMENT } from '../elements/ac-bs-form.element';
import { AC_BUILDER_BS_IMAGE_ELEMENT } from '../elements/ac-bs-image.element';
import { AC_BUILDER_BS_INPUT_ELEMENT } from '../elements/ac-bs-input.element';
import { AC_BUILDER_BS_INPUT_GROUP_ELEMENT } from '../elements/ac-bs-input-group.element';
import { AC_BUILDER_BS_LIST_GROUP_ELEMENT } from '../elements/ac-bs-list-group.element';
import { AC_BUILDER_BS_MODAL_ELEMENT } from '../elements/ac-bs-modal.element';
import { AC_BUILDER_BS_NAVBAR_ELEMENT } from '../elements/ac-bs-navbar.element';
import { AC_BUILDER_BS_NAVS_ELEMENT } from '../elements/ac-bs-navs.element';
import { AC_BUILDER_BS_OFFCANVAS_ELEMENT } from '../elements/ac-bs-offcanvas.element';
import { AC_BUILDER_BS_PAGINATION_ELEMENT } from '../elements/ac-bs-pagination.element';
import { AC_BUILDER_BS_POPOVER_ELEMENT } from '../elements/ac-bs-popover.element';
import { AC_BUILDER_BS_PROGRESS_ELEMENT } from '../elements/ac-bs-progress.element';
import { AC_BUILDER_BS_RADIO_ELEMENT } from '../elements/ac-bs-radio.element';
import { AC_BUILDER_BS_RANGE_ELEMENT } from '../elements/ac-bs-range.element';
import { AC_BUILDER_BS_ROW_ELEMENT } from '../elements/ac-bs-row.element';
import { AC_BUILDER_BS_SCROLLSPY_ELEMENT } from '../elements/ac-bs-scrollspy.element';
import { AC_BUILDER_BS_SELECT_ELEMENT } from '../elements/ac-bs-select.element';
import { AC_BUILDER_BS_STACK_ELEMENT } from '../elements/ac-bs-stack.element';
import { AC_BUILDER_BS_SWITCH_ELEMENT } from '../elements/ac-bs-switch.element';
import { AC_BUILDER_BS_TABLE_ELEMENT } from '../elements/ac-bs-table.element';
import { AC_BUILDER_BS_TABS_ELEMENT } from '../elements/ac-bs-tabs.element';
import { AC_BUILDER_BS_TEXTAREA_ELEMENT } from '../elements/ac-bs-textarea.element';
import { AC_BUILDER_BS_TOAST_ELEMENT } from '../elements/ac-bs-toast.element';
import { AC_BUILDER_BS_TYPOGRAPHY_ELEMENT } from '../elements/ac-bs-typography.element';
export function acRegisterBootstrapBuilderElements(){
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_ACCORDION_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_ALERT_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_BADGE_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_BREADCRUMB_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_BUTTON_GROUP_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_BUTTON_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_CARD_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_CAROUSEL_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_CHECKBOX_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_COLLAPSE_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_COL_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_CONTAINER_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_DROPDOWN_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_FIGURE_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_FLOATING_LABEL_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_FORM_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_IMAGE_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_INPUT_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_INPUT_GROUP_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_LIST_GROUP_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_MODAL_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_NAVBAR_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_NAVS_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_OFFCANVAS_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_PAGINATION_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_POPOVER_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_PROGRESS_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_RADIO_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_RANGE_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_ROW_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_SCROLLSPY_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_SELECT_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_STACK_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_SWITCH_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_TABLE_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_TABS_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_TEXTAREA_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_TOAST_ELEMENT});
  AcBuilderElementsManager.register({element:AC_BUILDER_BS_TYPOGRAPHY_ELEMENT});
  console.log(AcBuilderElementsManager);
}
