export const AcEnumDatagridEvent = {
  // activeRowChange: 'activeRowChange',
  CellBlur: 'cellBlur',
  CellClick: 'cellClick',
  CellDoubleClick: 'cellDoubleClick',
  CellDrag: 'cellDrag',
  CellDragEnd: 'cellDragEnd',
  CellDragEnter: 'cellDragEnter',
  CellDragLeave: 'cellDragLeave',
  CellDragOver: 'cellDragOver',
  CellDragStart: 'cellDragStart',
  CellDragDrop: 'cellDragDrop',
  CellEditorElementInit: 'cellEditorElementInit',
  // cellEditingStart: 'cellEditingStarted',
  // cellEditingStop: 'cellEditingStopped',
  CellFocus: 'cellFocus',
  CellHover: 'cellHover',
  CellKeyDown: 'cellKeyDown',
  CellKeyPress: 'cellKeyPress',
  CellKeyUp: 'cellKeyUp',
  CellMouseDown: 'cellMouseDown',
  CellMouseEnter: 'cellMouseEnter',
  CellMouseLeave: 'cellMouseLeave',
  CellMouseMove: 'cellMouseMove',
  CellMouseOver: 'cellMouseOver',
  CellMouseUp: 'cellMouseUp',
  CellRendererElementInit: 'cellRendererElementInit',
  CellTouchCancel: 'cellTouchCancel',
  CellTouchEnd: 'cellTouchEnd',
  CellTouchMove: 'cellTouchMove',
  CellTouchStart: 'cellTouchStart',
  // cellMouseOver: 'cellMouseOver',
  // cellSelectionChange: 'cellSelectionChanged',
  // cellValueChange: 'cellValueChanged',
  ColDefsSet: 'colDefsSet',
  // columnHeaderClick: 'columnHeaderClicked',


  ColumnBlur: 'columnBlur',
  ColumnClick: 'columnClick',
  ColumnDoubleClick: 'columnDoubleClick',
  ColumnDragEnd: 'columnDragEnd',
  ColumnDragEnter: 'columnDragEnter',
  ColumnDragLeave: 'columnDragLeave',
  ColumnDragOver: 'columnDragOver',
  ColumnDragStart: 'columnDragStart',
  ColumnDragDrop: 'columnDragDrop',
  ColumnFocus: 'columnFocus',
  ColumnHover: 'columnHover',
  ColumnKeyDown: 'columnKeyDown',
  ColumnKeyPress: 'columnKeyPress',
  ColumnKeyUp: 'columnKeyUp',
  ColumnMouseDown: 'columnMouseDown',
  ColumnMouseEnter: 'columnMouseEnter',
  ColumnMouseLeave: 'columnMouseLeave',
  ColumnMouseMove: 'columnMouseMove',
  ColumnMouseOver: 'columnMouseOver',
  ColumnMouseUp: 'columnMouseUp',
  ColumnTouchCancel: 'columnTouchCancel',
  ColumnTouchEnd: 'columnTouchEnd',
  ColumnTouchMove: 'columnTouchMove',
  ColumnTouchStart: 'columnTouchStart',

  ColumnResize: 'columnResize',
  ColumnSortChange: 'columnSortChange',
  ColumnFilterChange: 'columnFilterChange',
  ColumnPositionChange: 'columnPositionChange',
  DisplayedRowsChange: 'displayedRowsChange',
  // filterChanged: 'filterChanged',
  // filterModified: 'filterModified',
  // filterOpened: 'filterOpened',
  // paginationChanged: 'paginationChanged',
  RowAdd: 'rowAdd',
  RowBlur: 'rowBlur',
  RowClick: 'rowClick',
  RowDelete: 'rowDelete',
  RowDoubleClick: 'rowDoubleClick',
  RowDrag: 'rowDrag',
  RowDragEnd: 'rowDragEnd',
  RowDragEnter: 'rowDragEnter',
  RowDragLeave: 'rowDragLeave',
  RowDragOver: 'rowDragOver',
  RowDragStart: 'rowDragStart',
  RowDragDrop: 'rowDragDrop',
  RowFocus: 'rowFocus',
  RowHover: 'rowHover',
  RowKeyDown: 'rowKeyDown',
  RowKeyPress: 'rowKeyPress',
  RowKeyUp: 'rowKeyUp',
  RowMouseDown: 'rowMouseDown',
  RowMouseEnter: 'rowMouseEnter',
  RowMouseLeave: 'rowMouseLeave',
  RowMouseMove: 'rowMouseMove',
  RowMouseOver: 'rowMouseOver',
  RowMouseUp: 'rowMouseUp',
  RowTouchCancel: 'rowTouchCancel',
  RowTouchEnd: 'rowTouchEnd',
  RowTouchMove: 'rowTouchMove',
  RowTouchStart: 'rowTouchStart',
  // rowDataUpdated: 'rowDataUpdated',
  // rowDoubleClicked: 'rowDoubleClicked',
  // rowDragEnd: 'rowDragEnd',
  // rowDragStart: 'rowDragStart',
  // rowEditingStarted: 'rowEditingStarted',
  // rowEditingStopped: 'rowEditingStopped',
  RowPositionChange: 'rowPositionChange',
  RowUpdate: 'rowUpdate',
  // rowValueChanged: 'rowValueChanged',
  // selectionChanged: 'selectionChanged',
  // sortChanged: 'sortChanged',
  // stateUpdated: 'stateUpdated',
  // treeClose: 'treeClose',
  // treeOpen: 'treeOpen',
  // treeToggle: 'treeToggle',
  TotalRowsChange: 'totalRowsChange'
}
