export const AcEnumDatagridHook = {
  BeforeColDefsChange: 'beforeColDefsChange',
  BeforeDataChange: 'beforeDataChange',
  BeforeHeaderColumnCellsCreated: 'beforeHeaderColumnCellsCreated',
  BeforeRowCellsCreated: 'beforeRowCellsCreated',
  BodyCreated: 'bodyCreated',
  ColDefsChange: 'colDefsChange',
  ColumnFilterChange: 'columnFilterChange',
  ColumnResize: 'columnResize',
  ColumnSortChange: 'columnSortChange',
  DataChange: 'dataChange',
  DatagridCellCreated: 'datagridCellCreated',
  DatagridColumnCreated: 'datagridColumnCreated',
  DatagridRowCreated: 'datagridRowCreated',
  DataSourceTypeChange: 'dataSourceTypeChange',
  DisplayedRowsChange: 'displayedRowsChange',
  ExtensionEnabled: 'extensionEnabled',
  FooterCreated: 'footerCreated',
  HeaderCreated: 'headerCreated',
  HeaderColumnCellsCreated: 'headerColumnCellsCreated',
  RowCellsCreated: 'rowCellsCreated',
  RowAdd: 'rowAdd',
  RowFocus: 'rowFocus',
  RowDelete: 'rowDelete',
  RowUpdate: 'rowUpdate',
  TotalRowsChange: 'totalRowsChange',
  UsePaginationChange: 'usePaginationChange'
}
